mod "boxen",       "3.2.0", :github_tarball => "boxen/puppet-boxen"
mod "repository",  "2.3.0", :github_tarball => "boxen/puppet-repository"
mod "stdlib",      "4.3.2", :github_tarball => "puppetlabs/puppetlabs-stdlib"
